################################################
# Server configurations
################################################
server:
  connector:
    # Changing port is available for embedded server only
    # Is is not possible to change port for deploying application on external server
    port: ${PORT:8080}


################################################
# Application (global) configurations
################################################
application:
  # License path
  # Absolute or relative path to GroupDocs license file
  licensePath: ${LIC_PATH:}
  # Host name or ip for server instance
  hostAddress: ${HOST_ADDRESS:}

################################################
# Common configurations
################################################
common:
  # File rewriting on document uploading
  # Set false to keep both files
  # Set true to replace files with same name
  rewrite: ${REWRITE:true}
  # Page navigation
  # Set false to disable document navigation (go to next, previous, last and first page)
  pageSelector: true
  # Document download
  # Set false to disable document download
  download: ${DOWNLOAD_ON:true}
  # Document upload—É
  # Set false to disable document upload
  upload: ${UPLOAD_ON:true}
  # Document print
  # Set false to disable document print
  print: ${PRINT_ON:true}
  # File browser
  # Set false to disable document browse
  browse: ${BROWSE_ON:true}
  # Set false to disable right mouse click
  enableRightClick: ${RIGHTCLICK_ON:true}

################################################
# GroupDocs.Viewer configurations
################################################
viewer:
  # Files directory path
  # Absolute or relative path to files directory
  filesDirectory: ${FILES_DIR:DocumentSamples}
  # Fonts path
  # Absolute path to custom fonts directory
  fontsDirectory:
  # Default document
  # Absolute path to default document
  defaultDocument:
  # HTML rendering mode
  # Set false for image mode
  # Set true for HTML mode
  htmlMode: true
  # Pages preload
  # How many pages from a document should be loaded, remaining pages will be loaded on page scrolling
  # Set 0 to load all pages at once
  preloadPageCount: 0
  # Document zoom
  # Set false to disable document zooming
  zoom: true
  # Document search
  # Set false to disable document text search
  search: true
  # Thumbnails
  # Set false to disable thumbnails
  thumbnails: true
  # Page rotation
  # Set false to disable pages rotation
  rotate: true
  # Using cache
  # Set true to enable cache
  cache: true
  # Set true to enable page rotation saving
  saveRotateState: true
  # Enter text which will be used as a watermark
  watermarkText:
  # Print secured documents mode
  # Set false to ignore document print security
  # Set true to check document print security
  printAllowed: true
  # Set true to show grid lines
  showGridLines: true
  # Set cache folder name
  cacheFolderName: cache